export const CREATE_USER = "CREATE_USER"
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CLEAR_CATEGORY_REPLY = 'CLEAR_CATEGORY_REPLY';
export const READ_CATEGORY = 'READ_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
