export const CREATE_USER = "CREATE_USER"
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const CLEAR_CATEGORY_REPLY = 'CLEAR_CATEGORY_REPLY';
export const READ_CATEGORY = 'READ_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
